### PR TITLE
WIP: Should the accessor listings for local accessor, for example, be a partial specialization?

### PR DESCRIPTION
**Pull request by mkinsner**
If this makes sense to you Ronan, I can make the change for the variety of specializations.

### CODE REVIEW

**Comment by fraggamuffin** [comment]
Aug 12:
*  seems like a copy paste error, so need to be confirmed to see if there was actual reason behind this.

**Comment by AerialMantis** [comment]
@keryell local accessors are not permitted to be placeholders, this is mentioned in Table 4.47, we could perhaps include this in the specialisation to make that clearer.

**Comment by keryell** [comment]
> @keryell local accessors are not permitted to be placeholders, this is mentioned in Table 4.47, we could perhaps include this in the specialisation to make that clearer.

Yes we can specialize it with `access::placeholder::false_t`

**Comment by keryell** [comment]
Still a WIP about specializing it with `access::placeholder::false_t`

**Comment by keryell** [comment]
Discussed during Tuesday 2020/02/18 informal meeting:
still waiting for https://github.com/KhronosGroup/SYCL-Docs/pull/17 to move first

**Comment by keryell** [comment]
#### 2021/09/02 SYCL Khronos committee meeting
In SYCL 2020 we deprecated some targets and created specific types instead.
Just close without merging.

**Pull request closed without merging**
