### PR TITLE
Remove get_size() for image accessors and add missing get_range() definitions

### PR DESCRIPTION
**Pull request by AerialMantis**
This pull request proposes that we remove the `get_size()` member function for image accessors as it cannot be efficiently implemented within device code since OpenCL does not make any guarantees as to the position and padding of the elements of an image in device memory.

This change also adds missing `get_range` definitions for image and local accessors, and introduces an improved wording for all `get_range` definitions.

This pull request, if approved will replace https://github.com/KhronosGroup/SYCL-Docs/pull/27.

### CODE REVIEW

**Comment by garimagu** [comment]
>This pull request, if approved will replace #27.
Can you clarify this statement for me?
PR#27 later suggests to replace the get_size() method with get_range() method.
In this PR, are you suggesting we should have neither of them?

**Comment by AerialMantis** [comment]
@garimagu you make a good point about the change regarding `get_range`, I have included a change to introduce the missing `get_range` definitions in this in the pull request as well.

**Comment by keryell** [comment]
Codeplay to provide a CTS equivalent PR.

**Comment by keryell** [comment]
@AerialMantis you need to clarify commits from "Gordon" vis-à-vis the CLA.

**Comment by AerialMantis** [comment]
I have rebased and amended the author to fix the CLA issue, no functionality changes were made.

**Comment by bader** [comment]
https://github.com/KhronosGroup/SYCL-CTS/pull/35 has been merged. Should we merge the spec change as well?

**Comment by AerialMantis** [comment]
SYCL working group: Almost ready to merge, just waiting for an additional change to the specification to clarify on image_array accessors:
`range<dimensions> get_range()` -> `range<dimensions + 1> get_range()`
in order to match the range passed to the accessor constructor.

**Comment by keryell** [comment]
Merged during 2020/02/18 meeting

**Pull request merged**
