### PR TITLE
Updated 4.6.5.2 queue shortcut functions example. malloc_device needs…

### PR DESCRIPTION
**Pull request by pkeir**
… at least two arguments.

### CODE REVIEW

**Review by gmlueck — APPROVED** [review]

**Review by keryell — APPROVED** [review]

**Comment by keryell** [comment]
While you are working on this, it would be nice to add a `sycl::free` in the USM examples.
Otherwise it will give the idea that bad programming is a good way to have USM code shorter than one with buffer and accessor. :-)

**Review by keryell — COMMENTED** [review]
Also split the commit line to follow the classical git commit format with a blank line in the middle
```
Updated 4.6.5.2 queue shortcut functions example

malloc_device needs at least two arguments.
```

**Comment by pkeir** [comment]
I've updated the commit message. I'll submit the `sycl::free` change as a separate PR.

**Review by keryell — APPROVED** [review]
Yes, good to have the missing `free` in another PR.

**Review by ProGTX — APPROVED** [review]

**Comment by keryell** [comment]
Meeting 2021/07/08:

Lacking `free()`  to have in another PR.

**Pull request merged**
