### PR TITLE
Adding notes for pointer aliasing

### PR DESCRIPTION
**Pull request by Michoumichmich**
Following: https://github.com/KhronosGroup/SYCL-Docs/issues/191

### CODE REVIEW

**Review by ProGTX — APPROVED** [review]

**Review by keryell — COMMENTED** [review]
Actually in the specifications notes are typeset like this:
```asciidoc
[NOTE]
====
Information within a note callout, such as this text, is for informational purposes
and does not impose requirements on or specify behavior of a SYCL implementation.
====
```
to give https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:nonnormativerefs

Probably it makes sense to go along this representation if possible.

**Comment by fraggamuffin** [comment]
editorial issue remains

**Comment by keryell** [comment]
@Michoumichmich do you have time to update the issue or I can do it?

**Comment by Michoumichmich** [comment]
Hi @keryell, it's done :) Sorry for the delay, I had exams and I didn't had the time to do it right away.

**Review by keryell — APPROVED** [review]

**Comment by fraggamuffin** [comment]
LGTM; Michoumichmich please add yourself as contributor, congratulation on your first contribution.

**Pull request merged**
