### PR TITLE
Clarify image formats when multiple OpenCL implementations, and on the host device

### PR DESCRIPTION
**Pull request by mkinsner**
Resolves internal Khronos issue: https://gitlab.khronos.org/sycl/Specification/issues/219

### CODE REVIEW

**Comment by fraggamuffin** [comment]
Aug 12:
*   awaiting reviewers

**Comment by keryell** [comment]
We need to know what we globally support, so just say it is implementation defined in SYCL 1.2.1.

But waiting for the return of Mike Kinsner.

**Comment by keryell** [comment]
2019/09/26: Codeplay proposes to implement all OpenCL-supported formats on the host device.

**Comment by keryell** [comment]
2019/09/29: Codeplay will update this MR with new wording.

**Comment by AerialMantis** [comment]
I've have created a new pull request with the wording change discussed - https://github.com/KhronosGroup/SYCL-Docs/pull/63

**Comment by keryell** [comment]
Closing since it seems well subsumed by quite more detailed https://github.com/KhronosGroup/SYCL-Docs/pull/63

**Pull request closed without merging**
