### PR TITLE
Move cl::sycl::memory_order, atomic class and atomic operations to sycl namespace

### PR DESCRIPTION
**Pull request by VerenaBeckham**
Developers can use sycl::memory_order.

### CODE REVIEW

**Review by gmlueck — APPROVED** [review]

**Comment by bader** [comment]
Should we add a note about this change to https://github.com/KhronosGroup/SYCL-Docs/blob/SYCL-2020/master/adoc/chapters/what_changed.adoc?

**Comment by gmlueck** [comment]
I don't think this PR changes anything relative to SYCL 1.2.1.  We just removed a redundant definition of the `memory_order` enumeration from the spec.  The enumeration is still available in SYCL 2020, and it is still defined elsewhere in the spec.

**Comment by AerialMantis** [comment]
I think this change makes sense, though on it's own I this will be a breaking change for the deprecated `atomic` class as that relies on the definition of the `memory_order` in the `cl::sycl` namespace.

Technically in SYCL 2020 the `sycl` and `cl::sycl` namespaces are synonymous with each other if the `CL/sycl.hpp` header is included, so the intention is that this would be equivalent to having this in the `sycl` namespace, but having an interface still explicitly defined in the `cl::sycl` namespace suggests this is an exception to the rule.

From what I can tell this synopsis, the following synopsis for deprecated atomic free functions and a couple of member functions in the accessor synopsis are the only places where the `cl::sycl` namespace is still explicitly used, I think we should extend this PR to also switch from `cl::sycl` to `sycl` here to avoid any confusion.

**Comment by gmlueck** [comment]
> From what I can tell this synopsis, the following synopsis for deprecated atomic free functions and a couple of member functions in the accessor synopsis are the only places where the `cl::sycl` namespace is still explicitly used, I think we should extend this PR to also switch from `cl::sycl` to `sycl` here to avoid any confusion.

I think this makes sense.  At one point, we discussed the possibility of structuring the header file so that deprecated APIs are only available when `<CL/sycl.hpp>` is included, but that never made it into the spec.  I suspect the fact that the `atomic` interface is documented in the `cl::sycl` namespace is a holdover from that thinking.  At this point, there is no correlation between deprecated APIs and the `cl::sycl` namespace, so I think we should just document `atomic` in the `sycl` namespace.

**Comment by VerenaBeckham** [comment]
I also moved the atomic class and atomic operations into the sycl namespace.

**Comment by gmlueck** [comment]
> I also moved the atomic class and atomic operations into the sycl namespace.

Thanks, this looks good!

**Review by keryell — APPROVED** [review]
Thanks!

**Review by AerialMantis — APPROVED** [review]
Looks good, thanks!

**Comment by tomdeakin** [comment]
One more review.

**Review by TApplencourt — APPROVED** [review]

**Comment by tomdeakin** [comment]
WG approved to merge

**Pull request merged**
